spring.application.name=noteservice

spring.datasource.url=jdbc:h2:file:./data/notesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

palatine.base-url=https://api.palatine.ru/api/v1
palatine.model=palatine_large_highspeed
palatine.token=${PALATINE_API_TOKEN}